### ISSUE TITLE
Bugs : with appstore release due to using of deprecated API

### ISSUE THREAD

**Issue by mohadel92** [stacktiger/flutter_auth#5] opened 2021-06-19 16:30 UTC
i would like to enform  the users of this package that using it with flutter 1.22.5 or 1.22.6 causes 
installation of older version of flutter_web_view package that causes using of deprecated API
called UIWebView

Apple refusal message
<a href="https://ibb.co/BgMvtkX"><img src="https://i.ibb.co/MR0KsdY/Screen-Shot-2021-06-19-at-6-25-28-PM.png" alt="Screen-Shot-2021-06-19-at-6-25-28-PM" border="0"></a>

<a href="https://ibb.co/w0xfc6X"><img src="https://i.ibb.co/RvVqjHm/Whats-App-Image-2021-06-17-at-7-08-08-PM.jpg" alt="Whats-App-Image-2021-06-17-at-7-08-08-PM" border="0"></a>

<a href="https://ibb.co/w6qrQ6f"><img src="https://i.ibb.co/Svg7mvz/Whats-App-Image-2021-06-17-at-7-09-30-PM.jpg" alt="Whats-App-Image-2021-06-17-at-7-09-30-PM" border="0"></a>

**Comment by helenaford** [comment] 2021-06-19 17:50
Ah, sorry, it caused the rejection :(, thank you for reporting it. I'll be able to look into this soon but if you have an immediate fix, I'll be happy to merge it.  🙏

**Comment by kirstywilliams** [comment] 2021-06-22 15:40
@mohadel92 I'm closing this issue as this library is not the cause. We are only using versions of the officially maintained flutter plugins that all use WKWebView and not UIWebView.

**Closed as completed by kirstywilliams** 2021-06-22 15:40 UTC

**Comment by mohadel92** [comment] 2021-06-23 14:22
@kirstywilliams regarding flutter 1.22.6 
flutter_auth is using an older version
i have wasted hours and hours debugging this issue
archiving and uploading then rejection
at least show me some respect and discuss the issue
closing the issue without any discussion wont fix any thing

**Comment by ArjanAswal** [comment] 2021-06-24 09:27
@mohadel92 `flutter_auth` uses `flutter_webview_plugin: ^0.3.11` and UIWebView was replaced in `flutter_webview_plugin: ^0.1.5`. This package neither uses `webview_flutter` nor `flutter_web_view`.

It's easy to blame other people for your own mistakes and on top of that being rude about it. What's hard is to see is your own shortcomings and working on them.

Peace out 🤞
